[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/notes/programming/programming-languages/cpp-refresher/"
  to = "/notes/computer-science/programming-languages/cpp-refresher/"
  status = 301
  force = true
  query = {path = ":path"}
