[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://www.mauriciopoppe.com/notes/programming/programming-languages/cpp-refresher/index.html"
  to = "https://www.mauriciopoppe.com/"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "https://www.mauriciopoppe.com/notes/programming/programming-languages/cpp-refresher/"
  to = "https://www.mauriciopoppe.com/"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "https://www.mauriciopoppe.com/notes/programming/programming-languages/cpp-refresher/*"
  to = "https://www.mauriciopoppe.com/"
  status = 301
  force = true
  query = {path = ":path"}
