title: "Mauricio Poppe's notes"

params:
  description: "My notes about the things I learn every day"
  favicon: "favicon/favicon.ico"
  logo: "https://mauriciopoppe.com/images/2017-square.jpg"

author:
  name: "Mauricio Poppe"
  github: mauriciopoppe
  linkedin: mauriciopoppe
  twitter: mauricio_poppe

baseURL: "https://www.mauriciopoppe.com/"
languageCode: "en-us"

metadataFormat: 'yaml'
enableGitInfo: true

markup:
  highlight:
    # syntax is highlighted by prism
    codeFences: false
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
